[package]
name = "rustatic"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Web server for static site used primarily locally during development"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_http = "0.12"
clap = { version = "4.3", features = ["derive"] }
